title: Chinmay Rozekar Portfolio
baseurl: "/AI_ML_projects"
url: "https://chinmayrozekar.github.io"

# Build settings
markdown: kramdown
theme: minima

# Navigation settings
header_pages:
  - README.md
